version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: bootstrap-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=bootstrap-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces;'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  cassandra_data:
    driver: local